"""
Django settings for meebun_erp project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from django.templatetags.static import static

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-jtp%$=4w-=*kjvxs!4(nj$+coum#3t-h-7^vfa2k)i#2mefju#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.railway.app']
# 1. ยืนยันว่าโดเมนของ Railway นี้เราเชื่อถือ (ต้องใส่ https:// ด้วยนะคะ)
CSRF_TRUSTED_ORIGINS = [
    "https://erp-production-3d70.up.railway.app",
    "https://*.railway.app" # เผื่อกรณีมีการเปลี่ยนชื่อโดเมนในอนาคต
]

# 2. บอกให้ Django รู้ว่า Railway มีการใช้งานผ่าน Proxy ที่เป็น HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rangefilter',
    "stocks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware', # เพิ่มบรรทัดนี้ลงไป
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "meebun_erp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "meebun_erp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# หาบรรทัด DATABASES ของเก่า แล้ววางทับด้วยอันนี้ครับ
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# เพิ่ม 3 บรรทัดนี้ลงไปข้างล่าง DATABASES เพื่อบังคับใช้ SSL ครับ
# if not os.environ.get('RAILWAY_ENVIRONMENT_NAME') == '': # เช็กว่ารันบน Railway หรือเปล่า
#     DATABASES['default']['OPTIONS'] = {
#         'sslmode': 'require',
#     }
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Bangkok" # เปลี่ยนจาก UTC เป็นเวลาไทย
USE_TZ = True

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 1. ที่อยู่สำหรับเรียกใช้งานไฟล์ Static
STATIC_URL = "static/"

# 2. ที่อยู่สำหรับรวบรวมไฟล์ Static ทั้งหมดเพื่อส่งขึ้น Railway
STATIC_ROOT = BASE_DIR / "staticfiles"

# 3. ตัวช่วยให้ WhiteNoise จัดการไฟล์ (สำหรับ Django 6.0+)
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# บังคับให้คุกกี้ส่งผ่าน HTTPS เท่านั้น (Railway เป็น HTTPS)
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# เพิ่ม limit จำนวน fields ที่รับได้ต่อ request
# default คือ 1000 ซึ่งน้อยเกินไปเมื่อ SalesOrder มี item เยอะ
# (63 items × ~9 fields/row + inlines อื่นๆ = เกิน 1000 ได้ง่าย)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# ── Unfold Admin Theme ──────────────────────────────────────────────────────
UNFOLD = {
    "STYLES": [
        lambda request: static("css/admin_custom.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/date_range_picker.js"),
    ],
    "SITE_TITLE": "Meebun ERP",
    "SITE_HEADER": "Meebun ERP",
    "SITE_SYMBOL": "inventory_2",   # Google Material icon
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "COLORS": {
        "primary": {
            "50":  "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56  189 248",
            "500": "14  165 233",
            "600": "2   132 199",
            "700": "3   105 161",
            "800": "7   89  133",
            "900": "12  74  110",
            "950": "8   47  73",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "สินค้าและคลัง",
                "collapsible": True,
                "items": [
                    {"title": "กลุ่มสินค้า",           "icon": "category",       "link": "/admin/stocks/productcategory/"},
                    {"title": "รายการสินค้า (A4)",      "icon": "inventory_2",    "link": "/admin/stocks/product/"},
                    {"title": "ผู้จำหน่าย",             "icon": "storefront",     "link": "/admin/stocks/supplier/"},
                    {"title": "ลูกค้า",                 "icon": "people",         "link": "/admin/stocks/customer/"},
                ],
            },
            {
                "title": "การซื้อ",
                "collapsible": True,
                "items": [
                    {"title": "ใบสั่งซื้อ (B1)",        "icon": "shopping_cart",  "link": "/admin/stocks/purchaseorder/"},
                    {"title": "ติดตามนำเข้า (B4)",      "icon": "local_shipping", "link": "/admin/stocks/internationalpurchasetracking/"},
                    {"title": "สรุปรายจ่าย (C2)",        "icon": "summarize",      "link": "/admin/stocks/financereport/"},
                ],
            },
            {
                "title": "การขาย",
                "collapsible": True,
                "items": [
                    {"title": "ใบสั่งขาย (B2)",         "icon": "receipt_long",   "link": "/admin/stocks/salesorder/"},
                    {"title": "สรุปรายรับ (C3)",         "icon": "payments",       "link": "/admin/stocks/incomereport/"},
                    {"title": "รายงานยอดขาย (C5)",       "icon": "bar_chart",      "link": "/admin/stocks/salesreport/"},
                    {"title": "บัญชี DC/Rebate (C6)",   "icon": "account_balance","link": "/admin/stocks/shipmentaccounting/"},
                    {"title": "สรุปสัญญา Rebate (C7)",  "icon": "handshake",      "link": "/admin/stocks/rebatepayout/"},
                ],
            },
            {
                "title": "สัญญาและราคา",
                "collapsible": True,
                "items": [
                    {"title": "ราคาสัญญา (T2)",         "icon": "price_check",    "link": "/admin/stocks/customerproductcontract/"},
                    {"title": "สัญญาการขาย (T3)",        "icon": "description",    "link": "/admin/stocks/salescontract/"},
                ],
            },
            {
                "title": "วางแผนและผลิต",
                "collapsible": True,
                "items": [
                    {"title": "ตารางวางแผนสต็อก (C1)", "icon": "event_note",     "link": "/admin/stocks/stockplanning/"},
                    {"title": "ใบสั่งผลิต (B3)",        "icon": "factory",        "link": "/admin/stocks/productionorder/"},
                    {"title": "สูตรการผลิต (A5)",        "icon": "science",        "link": "/admin/stocks/bom/"},
                ],
            },
        ],
    },
}
