# Generated by Django 6.0.1 on 2026-02-03 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="ชื่อบริษัท"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=255, verbose_name="ชื่อคนติดต่อ"),
                ),
                ("address", models.TextField(verbose_name="ที่อยู่")),
                ("phone", models.CharField(max_length=50, verbose_name="เบอร์โทร")),
                (
                    "payment_term",
                    models.IntegerField(default=30, verbose_name="ระยะเวลาจ่ายเงิน (วัน)"),
                ),
                (
                    "vat",
                    models.DecimalField(decimal_places=2, default=7.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, verbose_name="ชื่อบริษัท"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=255, verbose_name="ชื่อคนติดต่อ"),
                ),
                ("address", models.TextField(verbose_name="ที่อยู่")),
                ("phone", models.CharField(max_length=50, verbose_name="เบอร์โทร")),
                (
                    "payment_term",
                    models.IntegerField(default=30, verbose_name="ระยะเวลาจ่ายเงิน (วัน)"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Domestic", "ในประเทศ"),
                            ("International", "ต่างประเทศ"),
                        ],
                        default="Domestic",
                        max_length=20,
                        verbose_name="ประเภท",
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=7.0,
                        max_digits=5,
                        verbose_name="Vat (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อสินค้า")),
                (
                    "barcode",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="บาร์โค้ด"
                    ),
                ),
                (
                    "has_bom",
                    models.BooleanField(default=False, verbose_name="มีสูตรการผลิต (BOM)"),
                ),
                ("category", models.CharField(max_length=100, verbose_name="กลุ่มสินค้า")),
                (
                    "buy_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคาซื้อ"
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="ราคาขาย",
                    ),
                ),
                (
                    "production_lead_time",
                    models.IntegerField(default=0, verbose_name="ระยะเวลาผลิต (วัน)"),
                ),
                (
                    "delivery_lead_time",
                    models.IntegerField(default=0, verbose_name="ระยะเวลาส่งมอบ (วัน)"),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(default=0, verbose_name="จำนวนคงเหลือ"),
                ),
                (
                    "unit",
                    models.CharField(default="ชิ้น", max_length=50, verbose_name="หน่วย"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้สร้าง",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stocks.supplier",
                        verbose_name="ผู้จำหน่าย",
                    ),
                ),
            ],
        ),
    ]
