# Generated by Django 6.0.1 on 2026-02-03 16:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_bom_bomingredient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bom",
            options={"verbose_name_plural": "5. สูตรการผลิต (BOM)"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name_plural": "3. ลูกค้า (Customer)"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "4. รายการสินค้า"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "1. กลุ่มสินค้า"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name_plural": "2. ผู้จำหน่าย (Supplier)"},
        ),
        migrations.RemoveField(
            model_name="bom",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="bom",
            name="production_time",
        ),
        migrations.RemoveField(
            model_name="bom",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="bom",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="bom",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="product",
            name="delivery_lead_time",
        ),
        migrations.RemoveField(
            model_name="product",
            name="production_lead_time",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="description",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="bom",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ชื่อสูตร"),
        ),
        migrations.AlterField(
            model_name="bom",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom_formula",
                to="stocks.product",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bomingredient",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="customer",
            name="payment_term",
            field=models.IntegerField(default=30, verbose_name="Credit (วัน)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="buy_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="ราคาทุน"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="has_bom",
            field=models.BooleanField(default=False, verbose_name="สินค้าผลิตเอง (BOM)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(default=0, verbose_name="สต็อกปัจจุบัน"),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="กลุ่มสินค้า"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="payment_term",
            field=models.IntegerField(default=30, verbose_name="Credit (วัน)"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="type",
            field=models.CharField(
                choices=[("Domestic", "ในประเทศ"), ("International", "ต่างประเทศ")],
                default="Domestic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="vat",
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5),
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pd_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("quantity_planned", models.PositiveIntegerField()),
                ("quantity_actual", models.PositiveIntegerField(default=0)),
                ("order_date", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "ร่าง"),
                            ("Started", "เริ่มผลิต"),
                            ("Finished", "ผลิตเสร็จ"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.product"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "8. ใบสั่งผลิต (Production)",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "invoice_no_supplier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="เลข Invoice ผู้ขาย"
                    ),
                ),
                ("order_date", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "ร่าง"),
                            ("Confirmed", "ยืนยัน"),
                            ("Received", "รับของแล้ว"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "6. ใบสั่งซื้อ (Purchase)",
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_ordered", models.PositiveIntegerField()),
                ("quantity_received", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.product"
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stocks.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "po_no_customer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="เลข PO ลูกค้า"
                    ),
                ),
                ("order_date", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "ร่าง"),
                            ("Confirmed", "ยืนยัน"),
                            ("Shipped", "ส่งของแล้ว"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "7. ใบสั่งขาย (Sales)",
            },
        ),
        migrations.CreateModel(
            name="SalesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_ordered", models.PositiveIntegerField()),
                ("quantity_shipped", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.product"
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stocks.salesorder",
                    ),
                ),
            ],
        ),
    ]
