# Generated by Django 6.0.1 on 2026-02-03 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_alter_bom_options_alter_customer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="bom",
            name="production_time",
            field=models.IntegerField(default=1, verbose_name="ระยะเวลาผลิต (วัน)"),
        ),
        migrations.AddField(
            model_name="bom",
            name="unit",
            field=models.CharField(default="ชิ้น", max_length=50, verbose_name="หน่วย"),
        ),
        migrations.AddField(
            model_name="bom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bom",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bom_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_lead_time",
            field=models.IntegerField(default=0, verbose_name="ระยะเวลาส่งมอบ (วัน)"),
        ),
        migrations.AddField(
            model_name="product",
            name="production_lead_time",
            field=models.IntegerField(default=0, verbose_name="ระยะเวลาผลิต (วัน)"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="bom",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bom_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="notes",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="quantity_actual",
            field=models.PositiveIntegerField(default=0, verbose_name="จำนวนที่ผลิตจริง"),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="quantity_planned",
            field=models.PositiveIntegerField(verbose_name="จำนวนที่วางแผน"),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="quantity_ordered",
            field=models.PositiveIntegerField(verbose_name="จำนวนที่สั่งซื้อ"),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="quantity_received",
            field=models.PositiveIntegerField(default=0, verbose_name="จำนวนที่รับจริง"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="quantity_ordered",
            field=models.PositiveIntegerField(verbose_name="จำนวนที่สั่งขาย"),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="quantity_shipped",
            field=models.PositiveIntegerField(default=0, verbose_name="จำนวนที่ส่งจริง"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="notes",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
    ]
