# Generated by Django 6.0.1 on 2026-02-03 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_bom_created_at_bom_production_time_bom_unit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="supplier",
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prod_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="production_time",
            field=models.IntegerField(default=1, verbose_name="เวลาผลิต (วัน)"),
        ),
        migrations.AlterField(
            model_name="bom",
            name="unit",
            field=models.CharField(default="ชิ้น", max_length=50, verbose_name="หน่วยผลิต"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prod_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="production_lead_time",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="ระยะเวลาผลิต (วัน)"
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="quantity_actual",
            field=models.PositiveIntegerField(default=0, verbose_name="ผลิตได้สะสม"),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "ร่าง"),
                    ("Started", "เริ่มผลิต"),
                    ("Finished", "เสร็จบางส่วน"),
                    ("Completed", "ปิดงาน/ครบถ้วน"),
                    ("Cancelled", "ยกเลิก"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="quantity_received",
            field=models.PositiveIntegerField(default=0, verbose_name="รับสะสม"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "ร่าง"),
                    ("Confirmed", "ยืนยัน"),
                    ("Received", "รับบางส่วน"),
                    ("Completed", "ปิดงาน/ครบถ้วน"),
                    ("Cancelled", "ยกเลิก"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="quantity_shipped",
            field=models.PositiveIntegerField(default=0, verbose_name="ส่งสะสม"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "ร่าง"),
                    ("Confirmed", "ยืนยัน"),
                    ("Shipped", "ส่งบางส่วน"),
                    ("Completed", "ปิดงาน/ครบถ้วน"),
                    ("Cancelled", "ยกเลิก"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="ชื่อบริษัท"),
        ),
        migrations.CreateModel(
            name="ProductionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished_date", models.DateTimeField(auto_now_add=True)),
                (
                    "quantity_finished",
                    models.PositiveIntegerField(verbose_name="จำนวนที่เสร็จครั้งนี้"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_logs",
                        to="stocks.productionorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="รหัสสินค้าฝั่ง Supplier"
                    ),
                ),
                (
                    "latest_buy_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ทุนล่าสุดจากเจ้านี้",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_suppliers",
                        to="stocks.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.supplier",
                        verbose_name="ผู้จำหน่าย",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "supplier")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="products",
                through="stocks.ProductSupplier",
                to="stocks.supplier",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseReceiptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_date", models.DateTimeField(auto_now_add=True)),
                (
                    "quantity_received",
                    models.PositiveIntegerField(verbose_name="จำนวนที่รับครั้งนี้"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_logs",
                        to="stocks.purchaseorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipped_date", models.DateTimeField(auto_now_add=True)),
                (
                    "quantity_shipped",
                    models.PositiveIntegerField(verbose_name="จำนวนที่ส่งครั้งนี้"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="stocks.salesorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
