# Generated by Django 6.0.1 on 2026-02-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0006_remove_product_supplier_product_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceReport",
            fields=[],
            options={
                "verbose_name_plural": "C2. รายงานสรุปการเงิน",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.purchaseorder",),
        ),
        migrations.CreateModel(
            name="StockPlanning",
            fields=[],
            options={
                "verbose_name_plural": "C1. ตารางการวางแผนสต็อก",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.product",),
        ),
        migrations.AlterModelOptions(
            name="bom",
            options={"verbose_name_plural": "A5. สูตรการผลิต (BOM)"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name_plural": "A3. ลูกค้า (Customer)"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "A4. รายการสินค้า"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "A1. กลุ่มสินค้า"},
        ),
        migrations.AlterModelOptions(
            name="productionorder",
            options={"verbose_name_plural": "B3. ใบสั่งผลิต (Production)"},
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={"verbose_name_plural": "B1. ใบสั่งซื้อ (Purchase)"},
        ),
        migrations.AlterModelOptions(
            name="salesorder",
            options={"verbose_name_plural": "B2. ใบสั่งขาย (Sales)"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name_plural": "A2. ผู้จำหน่าย (Supplier)"},
        ),
    ]
