# Generated by Django 6.0.1 on 2026-02-04 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_financereport_stockplanning_alter_bom_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereceiptlog",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="stocks.product",
                verbose_name="สินค้าที่รับ",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasereceiptlog",
            name="supplier_invoice",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="เลข Invoice/ใบส่งของ Supplier"
            ),
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="stocks.product",
                verbose_name="สินค้าที่ส่ง",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="shipping_no",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="เลขใบขนส่ง/Invoice ของเรา"
            ),
        ),
        migrations.AlterField(
            model_name="productionlog",
            name="finished_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันเวลาที่เสร็จ"),
        ),
        migrations.AlterField(
            model_name="productionlog",
            name="notes",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AlterField(
            model_name="productionlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้บันทึก",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceiptlog",
            name="notes",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AlterField(
            model_name="purchasereceiptlog",
            name="received_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันเวลาที่บันทึก"),
        ),
        migrations.AlterField(
            model_name="purchasereceiptlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้บันทึก",
            ),
        ),
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="notes",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="shipped_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันเวลาที่ส่ง"),
        ),
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้บันทึก",
            ),
        ),
    ]
