# Generated by Django 6.0.1 on 2026-02-04 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0008_purchasereceiptlog_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bom",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom_formulas",
                to="stocks.product",
            ),
        ),
    ]
