# Generated by Django 6.0.1 on 2026-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0010_alter_product_options_remove_product_barcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="ชื่อแท็ก"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="สีแท็ก (Hex)"
                    ),
                ),
            ],
            options={
                "verbose_name": "แท็กสินค้า",
                "verbose_name_plural": "แท็กสินค้าทั้งหมด",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "A4. รายการสินค้า (Product)"},
        ),
        migrations.AlterModelOptions(
            name="productbarcode",
            options={},
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="stocks.producttag",
                verbose_name="แท็ก",
            ),
        ),
    ]
