# Generated by Django 6.0.1 on 2026-02-05 03:43

import stocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0011_producttag_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttag",
            options={"verbose_name_plural": "T1. แท็กสินค้า (Product Tag)"},
        ),
        migrations.AddField(
            model_name="product",
            name="is_product",
            field=models.BooleanField(default=True, verbose_name="เป็นสินค้า (สต็อก)"),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="color",
            field=models.CharField(
                default=stocks.models.get_random_color,
                max_length=7,
                verbose_name="สีแท็ก (Hex)",
            ),
        ),
    ]
