# Generated by Django 6.0.1 on 2026-02-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0012_alter_producttag_options_product_is_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesitem",
            name="auto_produce",
            field=models.BooleanField(default=False, verbose_name="ผลิตทันที (Auto PD)"),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="is_produced",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
