# Generated by Django 6.0.1 on 2026-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0013_salesitem_auto_produce_salesitem_is_produced"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionorder",
            options={"verbose_name_plural": "B3. ใบสั่งผลิต (Productions)"},
        ),
        migrations.AlterModelOptions(
            name="producttag",
            options={
                "verbose_name": "แท็กสินค้า",
                "verbose_name_plural": "T1. แท็กสินค้า (Product Tag)",
            },
        ),
        migrations.AddField(
            model_name="producttag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="วันที่สร้าง"
            ),
        ),
    ]
