# Generated by Django 6.0.1 on 2026-02-05 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0014_alter_productionorder_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ราคา/หน่วย"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vat_percent",
            field=models.DecimalField(
                decimal_places=2, default=7.0, max_digits=5, verbose_name="VAT (%)"
            ),
        ),
        migrations.CreateModel(
            name="PurchasePaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ยอดที่จ่าย"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่จ่าย"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="หมายเหตุ/เลขที่สลิป"
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_logs",
                        to="stocks.purchaseorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้บันทึก",
                    ),
                ),
            ],
        ),
    ]
