# Generated by Django 6.0.1 on 2026-02-06 02:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0015_purchaseitem_unit_price_purchaseorder_vat_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeReport",
            fields=[],
            options={
                "verbose_name": "C3. สรุปรายรับ (Income Report)",
                "verbose_name_plural": "C3. สรุปรายรับ (Income Report)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.salesorder",),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "🔴 ยังไม่จ่าย"),
                    ("Partial", "🟠 จ่ายบางส่วน"),
                    ("Paid", "🟢 จ่ายครบแล้ว"),
                ],
                default="Unpaid",
                max_length=20,
                verbose_name="สถานะการจ่ายเงิน",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "🔴 ยังไม่รับเงิน"),
                    ("Partial", "🟠 รับเงินบางส่วน"),
                    ("Paid", "🟢 รับเงินครบแล้ว"),
                ],
                default="Unpaid",
                max_length=20,
                verbose_name="สถานะการรับเงิน",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "รอรับของ"),
                    ("Received", "รับของบางส่วน"),
                    ("Completed", "ได้รับสินค้าครบถ้วน"),
                    ("Cancelled", "ยกเลิก"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="สถานะเอกสาร (PO Status)",
            ),
        ),
        migrations.CreateModel(
            name="SalesPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="วันที่รับเงิน"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ยอดเงินที่รับ"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="หมายเหตุ"
                    ),
                ),
                (
                    "evidence",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="payment_evidence/",
                        verbose_name="หลักฐานการโอน",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="stocks.salesorder",
                    ),
                ),
            ],
        ),
    ]
