# Generated by Django 6.0.1 on 2026-02-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0016_incomereport_purchaseorder_payment_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IncomeReport",
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "รอรับของ"),
                    ("Received", "รับของบางส่วน"),
                    ("Completed", "ปิดงาน/ครบถ้วน"),
                    ("Cancelled", "ยกเลิก"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="สถานะเอกสาร (PO Status)",
            ),
        ),
        migrations.CreateModel(
            name="IncomeReport",
            fields=[
                (
                    "salesorder_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stocks.salesorder",
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=7.0,
                        max_digits=5,
                        verbose_name="ภาษีมูลค่าเพิ่ม (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "C3. สรุปรายรับ (Income Report)",
                "verbose_name_plural": "C3. สรุปรายรับ (Income Report)",
            },
            bases=("stocks.salesorder",),
        ),
    ]
