# Generated by Django 6.0.1 on 2026-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0017_delete_incomereport_alter_purchaseorder_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="vat_percent",
            field=models.DecimalField(
                decimal_places=2, default=7.0, max_digits=5, verbose_name="VAT (%)"
            ),
        ),
        migrations.DeleteModel(
            name="IncomeReport",
        ),
        migrations.CreateModel(
            name="IncomeReport",
            fields=[],
            options={
                "verbose_name": "C3. สรุปรายรับ (Income Report)",
                "verbose_name_plural": "C3. สรุปรายรับ (Income Report)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.salesorder",),
        ),
    ]
