# Generated by Django 6.0.1 on 2026-02-07 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0019_salesitem_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesitem",
            name="barcode_used",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="บาร์โค้ดที่ใช้"
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="dc_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="% DC"
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="rebate_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="% Rebate"
            ),
        ),
        migrations.CreateModel(
            name="CustomerProductContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ราคาขายเฉพาะเจ้า"
                    ),
                ),
                (
                    "dc_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="% DC"
                    ),
                ),
                (
                    "rebate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="% Rebate",
                    ),
                ),
                (
                    "barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stocks.productbarcode",
                        verbose_name="บาร์โค้ดเฉพาะเจ้า",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_contracts",
                        to="stocks.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "สัญญาราคาและบาร์โค้ด",
                "verbose_name_plural": "T2. สัญญาราคาและบาร์โค้ด",
                "unique_together": {("customer", "product")},
            },
        ),
    ]
