# Generated by Django 6.0.1 on 2026-02-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0020_salesitem_barcode_used_salesitem_dc_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[],
            options={
                "verbose_name": "C4. กำหนดรับเงิน (Payment Schedule)",
                "verbose_name_plural": "C4. กำหนดรับเงิน (Payment Schedule)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.salesorder",),
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="barcode_used",
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="dc_percent",
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="rebate_percent",
        ),
        migrations.AddField(
            model_name="customer",
            name="account_close_day",
            field=models.IntegerField(
                default=25, help_text="ระบุวันที่ 1-31", verbose_name="วันที่ตัดรอบบัญชี"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="payment_due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันกำหนดรับเงิน (Payment Due)"
            ),
        ),
        migrations.DeleteModel(
            name="CustomerProductContract",
        ),
    ]
