# Generated by Django 6.0.1 on 2026-02-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0021_paymentschedule_remove_salesitem_barcode_used_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentSchedule",
        ),
        migrations.CreateModel(
            name="ShipmentPaymentReport",
            fields=[],
            options={
                "verbose_name": "C4. รายงานกำหนดรับเงิน (แยกตามการส่ง)",
                "verbose_name_plural": "C4. รายงานกำหนดรับเงิน (แยกตามการส่ง)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.salesdeliverylog",),
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="payment_due_date",
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="payment_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันกำหนดรับเงิน"),
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="shipment_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="มูลค่าที่ส่งครั้งนี้"
            ),
        ),
    ]
