# Generated by Django 6.0.1 on 2026-02-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0022_delete_paymentschedule_shipmentpaymentreport_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipmentpaymentreport",
            options={
                "verbose_name": "C4. สรุปรับชำระ (ตามการส่ง)",
                "verbose_name_plural": "C4. สรุปรับชำระ (ตามการส่ง)",
            },
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="dc_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="ยอดหัก DC"
            ),
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="rebate_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="ยอดหัก Rebate"
            ),
        ),
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="shipment_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="ยอดรวมสินค้า (ก่อนหัก)",
            ),
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("ADD", "เพิ่มสต็อก (+)"), ("SUB", "ลดสต็อก (-)")],
                        default="ADD",
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="จำนวนที่ปรับ")),
                (
                    "reason",
                    models.CharField(max_length=255, verbose_name="หมายเหตุ/เหตุผล"),
                ),
                (
                    "adjustment_value",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "T3 บันทึกการปรับสต็อก",
            },
        ),
        migrations.CreateModel(
            name="CustomerProductContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคาสัญญา"
                    ),
                ),
                (
                    "dc_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="ค่า DC (%)",
                    ),
                ),
                (
                    "rebate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Rebate (%)",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "T2 ราคาสัญญา & DC/Rebate",
                "unique_together": {("customer", "product")},
            },
        ),
    ]
