# Generated by Django 6.0.1 on 2026-02-08 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0024_documentlock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="shipped_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="วันที่ส่งของ"
            ),
        ),
    ]
