# Generated by Django 6.0.1 on 2026-02-08 13:13

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0025_alter_salesdeliverylog_shipped_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="order_date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="shipped_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="วันที่ส่งของ",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="order_date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
