# Generated by Django 6.0.1 on 2026-02-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0026_alter_productionorder_order_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReport",
            fields=[],
            options={
                "verbose_name": "C5.รายงานยอดขายตามสินค้า",
                "verbose_name_plural": "C5.รายงานยอดขายตามสินค้า",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.product",),
        ),
        migrations.AlterModelOptions(
            name="customerproductcontract",
            options={"verbose_name_plural": "T2.ราคาสัญญา&DC/Rebate"},
        ),
        migrations.AlterModelOptions(
            name="stockadjustment",
            options={"verbose_name_plural": "T3.บันทึกการปรับสต็อก"},
        ),
    ]
