# Generated by Django 6.0.1 on 2026-02-09 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0027_salesreport_alter_customerproductcontract_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerproductcontract",
            options={"verbose_name_plural": "T2. ราคาสัญญา&DC/Rebate"},
        ),
        migrations.AlterModelOptions(
            name="salesreport",
            options={
                "verbose_name": "C5. รายงานยอดขายตามสินค้า",
                "verbose_name_plural": "C5. รายงานยอดขายตามสินค้า",
            },
        ),
        migrations.AlterModelOptions(
            name="stockadjustment",
            options={"verbose_name_plural": "T3. บันทึกการปรับสต็อก"},
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_items",
                to="stocks.product",
            ),
        ),
    ]
