# Generated by Django 6.0.1 on 2026-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0028_alter_customerproductcontract_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentAccounting",
            fields=[],
            options={
                "verbose_name": "C6. ตรวจสอบรายรับ & DC Rebate",
                "verbose_name_plural": "C6. ตรวจสอบรายรับ & DC Rebate",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.salesdeliverylog",),
        ),
        migrations.CreateModel(
            name="ShipmentReconciliation",
            fields=[],
            options={
                "verbose_name": "C6. ตรวจสอบรายรับและ Rebate (ตามใบส่ง)",
                "verbose_name_plural": "C6. ตรวจสอบรายรับและ Rebate (ตามใบส่ง)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.salesdeliverylog",),
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="confirmed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="is_dc_confirmed",
            field=models.BooleanField(default=False, verbose_name="ยืนยัน DC"),
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="is_rebate_confirmed",
            field=models.BooleanField(default=False, verbose_name="ยืนยัน Rebate"),
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="is_revenue_confirmed",
            field=models.BooleanField(default=False, verbose_name="ยืนยันยอดรับเงิน"),
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="payment_note",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="หมายเหตุการจ่าย"
            ),
        ),
    ]
