# Generated by Django 6.0.1 on 2026-02-10 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0029_shipmentaccounting_shipmentreconciliation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionMaterialUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_qty",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="จำนวนตามสูตร (Total)",
                    ),
                ),
                (
                    "actual_qty_to_use",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="จำนวนที่ต้องใช้จริง (ปรับแต่งได้)",
                    ),
                ),
                (
                    "used_so_far",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ตัดสต็อกไปแล้ว",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ShipmentReconciliation",
        ),
        migrations.AlterModelOptions(
            name="shipmentaccounting",
            options={
                "verbose_name": "C6. การทำบัญชี DC/Rebate",
                "verbose_name_plural": "C6. การทำบัญชี DC/Rebate",
            },
        ),
        migrations.AddField(
            model_name="productionorder",
            name="bom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.bom",
                verbose_name="สูตรที่ใช้ผลิต",
            ),
        ),
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="is_dc_confirmed",
            field=models.BooleanField(default=False, verbose_name="DC"),
        ),
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="is_rebate_confirmed",
            field=models.BooleanField(default=False, verbose_name="Rebate"),
        ),
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="is_revenue_confirmed",
            field=models.BooleanField(default=False, verbose_name="Paid"),
        ),
        migrations.AlterField(
            model_name="salesdeliverylog",
            name="quantity_shipped",
            field=models.PositiveIntegerField(verbose_name="จำนวน"),
        ),
        migrations.AddField(
            model_name="productionmaterialusage",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_usages",
                to="stocks.productionorder",
            ),
        ),
        migrations.AddField(
            model_name="productionmaterialusage",
            name="raw_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stocks.product",
                verbose_name="วัตถุดิบ/Package",
            ),
        ),
    ]
