# Generated by Django 6.0.1 on 2026-02-11 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0030_productionmaterialusage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternationalPurchaseTracking",
            fields=[],
            options={
                "verbose_name": "B4. ติดตามสินค้าต่างประเทศ (Import Tracking)",
                "verbose_name_plural": "B4. ติดตามสินค้าต่างประเทศ (Import Tracking)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.purchaseorder",),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="arrived_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่ถึงไทย"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="departed_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่ออกเดินทาง"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="loaded_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่ขึ้นตู้"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="paid_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่จ่ายเงิน"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="received_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่ถึงโกดัง"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="related_po",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.purchaseorder",
                verbose_name="อ้างอิง PO ที่เกี่ยวข้อง",
            ),
        ),
    ]
