# Generated by Django 6.0.1 on 2026-02-12 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0031_internationalpurchasetracking_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internationalpurchasetracking",
            options={
                "verbose_name": "B4. ติดตามสินค้าต่างประเทศ",
                "verbose_name_plural": "B4. ติดตามสินค้าต่างประเทศ",
            },
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="related_po",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.purchaseorder",
                verbose_name="Related PO",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "รอรับของ"),
                    ("Received", "รับของบางส่วน"),
                    ("Completed", "ปิดงาน/ครบถ้วน"),
                    ("Cancelled", "ยกเลิก"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="สถานะใบสั่งซื้อ",
            ),
        ),
    ]
