# Generated by Django 6.0.1 on 2026-02-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0032_alter_internationalpurchasetracking_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productbarcode",
            name="conversion_factor",
            field=models.PositiveIntegerField(default=1, verbose_name="ตัวคูณ"),
        ),
        migrations.AddField(
            model_name="productbarcode",
            name="unit_name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ชื่อหน่วย"
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="barcode_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.productbarcode",
                verbose_name="บาร์โค้ด/หน่วยขาย",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="quantity_unit",
            field=models.PositiveIntegerField(default=1, verbose_name="จำนวนที่สั่ง"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "🔴 ยังไม่จ่าย"),
                    ("Partial", "🟠 จ่ายบางส่วน"),
                    ("Paid", "🟢 จ่ายครบแล้ว"),
                ],
                default="Unpaid",
                max_length=20,
                verbose_name="สถานะการเงิน",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="received_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่ถึงโกดัง (ล่าสุด)"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "⚪ ร่าง (Draft)"),
                    ("Pending", "⏳ รอรับของ/สั่งซื้อแล้ว (Pending)"),
                    ("Confirmed", "🔵 ยืนยัน (Confirmed)"),
                    ("Ordered", "📝 สั่งซื้อแล้ว (Ordered)"),
                    ("Paid", "💰 จ่ายเงินแล้ว (Paid)"),
                    ("Loaded", "📦 ขึ้นตู้แล้ว (Loaded)"),
                    ("Departed", "🚢 ออกเดินทาง (Departed)"),
                    ("Arrived", "🏁 ถึงไทย (Arrived)"),
                    ("Received", "📥 รับของบางส่วน (Received)"),
                    ("Partially Received", "📥 รับของบางส่วน (Partial)"),
                    ("Completed", "✅ ปิดงาน/ครบถ้วน (Completed)"),
                    ("Cancelled", "❌ ยกเลิก (Cancelled)"),
                ],
                default="Pending",
                max_length=50,
                verbose_name="สถานะเอกสาร",
            ),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="quantity_ordered",
            field=models.PositiveIntegerField(default=0, verbose_name="จำนวนรวม (ชิ้น)"),
        ),
    ]
