# Generated by Django 6.0.1 on 2026-02-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0033_productbarcode_conversion_factor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesitem",
            name="bom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.bom",
                verbose_name="สูตรผลิต",
            ),
        ),
    ]
