# Generated by Django 6.0.1 on 2026-02-13 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0034_salesitem_bom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productbarcode",
            options={"verbose_name_plural": "T4. หน่วยขายตามบาร์โค้ด"},
        ),
        migrations.AlterField(
            model_name="productbarcode",
            name="conversion_factor",
            field=models.PositiveIntegerField(default=1, verbose_name="จำนวนต่อหน่วย"),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_items",
                to="stocks.product",
            ),
        ),
    ]
