# Generated by Django 6.0.1 on 2026-02-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0035_alter_productbarcode_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financereport",
            options={"verbose_name_plural": "C2. สรุปรายจ่าย (PO Report)"},
        ),
        migrations.AlterModelOptions(
            name="incomereport",
            options={
                "verbose_name": "C3. สรุปรายรับ (SO Report)",
                "verbose_name_plural": "C3. สรุปรายรับ (SO Report)",
            },
        ),
        migrations.AlterField(
            model_name="bomingredient",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="has_bom",
            field=models.BooleanField(default=False, verbose_name="มีBOM"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_product",
            field=models.BooleanField(default=True, verbose_name="เป็นสินค้ามีสต๊อก"),
        ),
        migrations.AlterField(
            model_name="productionmaterialusage",
            name="actual_qty_to_use",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=12,
                verbose_name="จำนวนที่ต้องใช้จริง (ปรับแต่งได้)",
            ),
        ),
        migrations.AlterField(
            model_name="productionmaterialusage",
            name="planned_qty",
            field=models.DecimalField(
                decimal_places=4, max_digits=12, verbose_name="จำนวนตามสูตร (Total)"
            ),
        ),
        migrations.AlterField(
            model_name="productionmaterialusage",
            name="used_so_far",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=12, verbose_name="ตัดสต็อกไปแล้ว"
            ),
        ),
    ]
