# Generated by Django 6.0.1 on 2026-02-22 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0036_alter_financereport_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_name",
                    models.CharField(max_length=255, verbose_name="ชื่อสัญญา/เลขที่สัญญา"),
                ),
                ("start_date", models.DateField(verbose_name="วันที่เริ่มสัญญา")),
                ("end_date", models.DateField(verbose_name="วันที่สิ้นสุดสัญญา")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="สถานะใช้งาน"),
                ),
                (
                    "payout_trigger",
                    models.CharField(
                        choices=[
                            ("END_OF_CONTRACT", "จ่ายครั้งเดียวเมื่อครบสัญญา"),
                            ("ANNIVERSARY", "จ่ายทุกวันครบรอบที่ระบุ (เช่น ทุกวันที่ 5 ของปี)"),
                            ("PERIODIC", "จ่ายตามรอบเงื่อนไข (เดือน/ไตรมาส/ปี)"),
                        ],
                        default="PERIODIC",
                        max_length=30,
                        verbose_name="เงื่อนไขการตัดจ่าย",
                    ),
                ),
                (
                    "payout_delay",
                    models.CharField(
                        choices=[
                            ("SAME_PERIOD", "จ่ายภายในเดือน/รอบที่เกิดยอดเลย"),
                            ("NEXT_PERIOD", "จ่ายในเดือน/รอบถัดไป"),
                            ("SPECIFIC_DAY", "จ่ายในวันที่ระบุของรอบถัดไป"),
                        ],
                        default="NEXT_PERIOD",
                        max_length=30,
                        verbose_name="จังหวะการโอนเงิน",
                    ),
                ),
                (
                    "payout_day",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="จ่ายวันที่ (ระบุตัวเลข 1-31)"
                    ),
                ),
                (
                    "next_payout_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="วันนัดจ่ายรอบถัดไป (ระบบคำนวณให้)",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RebatePayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="ยอดสะสมตั้งแต่วันที่")),
                ("period_end", models.DateField(verbose_name="ยอดสะสมถึงวันที่")),
                ("payout_date", models.DateField(verbose_name="กำหนดวันที่ต้องจ่าย")),
                (
                    "total_sales_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ยอดขายสะสมในรอบ"
                    ),
                ),
                (
                    "rebate_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="เงินที่ต้องจ่ายคืน"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "รอจ่าย"), ("PAID", "จ่ายแล้ว")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "ref_invoice",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="เลขที่ใบลดหนี้/ใบจ่ายเงิน"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.salescontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติการจ่ายเงินคืน (Rebate Payout)",
            },
        ),
        migrations.CreateModel(
            name="ContractCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TOTAL_SALES", "1. คำนวณจากยอดขายรวม"),
                            ("PRODUCT_BASED", "2. คำนวณตามสินค้า/กลุ่มสินค้า"),
                        ],
                        max_length=20,
                        verbose_name="ประเภทเงื่อนไข",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "รายเดือน"),
                            ("QUARTERLY", "รายไตรมาส"),
                            ("YEARLY", "รายปี"),
                            ("YTD", "ยอดรวมถึงปัจจุบัน (YTD)"),
                        ],
                        max_length=20,
                        verbose_name="รอบการคำนวณ",
                    ),
                ),
                (
                    "product_tag",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="กลุ่มสินค้า (Tag)"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("PERCENT_SALES", "% จากยอดขาย"),
                            ("AMOUNT_PER_QTY", "บาทต่อจำนวนชิ้น (เฉพาะแบบที่ 2)"),
                        ],
                        max_length=20,
                        verbose_name="วิธีคำนวณ",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="ค่าที่ระบุ (% หรือ บาท)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stocks.product",
                        verbose_name="สินค้าเฉพาะเจาะจง",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="stocks.salescontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "เงื่อนไขสัญญา",
            },
        ),
    ]
