# Generated by Django 6.0.1 on 2026-02-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0037_salescontract_rebatepayout_contractcondition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractcondition",
            options={
                "verbose_name": "C7. สัญญาการขาย",
                "verbose_name_plural": "C7. สัญญาการขาย",
            },
        ),
        migrations.RemoveField(
            model_name="contractcondition",
            name="product_tag",
        ),
        migrations.AddField(
            model_name="contractcondition",
            name="product_tag_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.producttag",
                verbose_name="กลุ่มสินค้า (Tag)",
            ),
        ),
        migrations.AddField(
            model_name="customerproductcontract",
            name="product_tag_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.producttag",
                verbose_name="กลุ่มสินค้า (Tag)",
            ),
        ),
    ]
