# Generated by Django 6.0.1 on 2026-03-02 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0038_alter_contractcondition_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractcondition",
            options={
                "verbose_name": "T3. สัญญาการขาย",
                "verbose_name_plural": "T3. สัญญาการขาย",
            },
        ),
        migrations.AlterModelOptions(
            name="productbarcode",
            options={"verbose_name_plural": "T5. หน่วยขายตามบาร์โค้ด"},
        ),
        migrations.AlterModelOptions(
            name="rebatepayout",
            options={
                "verbose_name": "สรุปสัญญา Rebate",
                "verbose_name_plural": "C7. สรุปสัญญา Rebate",
            },
        ),
        migrations.AlterModelOptions(
            name="salescontract",
            options={
                "verbose_name": "T3. สัญญาการขาย",
                "verbose_name_plural": "T3. สัญญาการขาย",
            },
        ),
        migrations.AlterModelOptions(
            name="stockadjustment",
            options={"verbose_name_plural": "T4. บันทึกการปรับสต็อก"},
        ),
        migrations.CreateModel(
            name="RebatePayoutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipped_date", models.DateTimeField(verbose_name="วันที่ส่งของ")),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_items",
                        to="stocks.salesdeliverylog",
                        verbose_name="รายการส่งของ",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stocks.rebatepayout",
                        verbose_name="ใบสรุป Rebate",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการส่งของในรอบ Rebate",
                "ordering": ["shipped_date"],
            },
        ),
    ]
