# Generated by Django 6.0.1 on 2026-03-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0039_add_rebate_payout_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractcondition",
            options={"verbose_name": "เงื่อนไขสัญญา", "verbose_name_plural": "เงื่อนไขสัญญา"},
        ),
        migrations.AddField(
            model_name="salesdeliverylog",
            name="barcode_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stocks.productbarcode",
                verbose_name="บาร์โค้ด/แพ็คเกจ",
            ),
        ),
    ]
