# Generated by Django 6.0.1 on 2026-08-07 14:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0055_purchaseorder_cancelled_at_salesorder_cancelled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdeliverylog',
            name='shipping_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='เลขใบขนส่ง/MB Invoice'),
        ),
        migrations.CreateModel(
            name='PurchaseQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pq_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('quote_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='วันที่ใบเสนอราคา')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.supplier', verbose_name='ผู้จำหน่าย')),
            ],
            options={
                'verbose_name': 'ใบเสนอราคาซื้อ',
                'verbose_name_plural': 'B5. ใบเสนอราคาซื้อ (Purchase Quotation)',
            },
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sq_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('quote_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='วันที่ใบเสนอราคา')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'ใบเสนอราคาขาย',
                'verbose_name_plural': 'B6. ใบเสนอราคาขาย (Sales Quotation)',
            },
        ),
        migrations.CreateModel(
            name='PurchaseQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาซื้อใหม่')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.product', verbose_name='สินค้า')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocks.purchasequotation')),
            ],
            options={
                'unique_together': {('quotation', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาขายใหม่')),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.productbarcode', verbose_name='บาร์โค้ด (ถ้าระบุ)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.product', verbose_name='สินค้า')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocks.salesquotation')),
            ],
            options={
                'unique_together': {('quotation', 'product')},
            },
        ),
    ]
