# Generated by Django 6.0.1 on 2026-08-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0056_alter_salesdeliverylog_shipping_no_purchasequotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_source',
            field=models.CharField(blank=True, choices=[('manual', 'กำหนดเอง'), ('bom', 'BOM'), ('supplier', 'Supplier +15%')], default='supplier', max_length=10, verbose_name='ที่มาต้นทุน'),
        ),
    ]
