# Generated by Django 6.0.1 on 2026-08-13 13:42

import django.db.models.deletion
from django.db import migrations, models


def backfill_quantity_unit(apps, schema_editor):
    """แถวเดิมยังไม่มี barcode_obj (factor=1) → quantity_unit ต้องเท่ากับ quantity_ordered เดิมเป๊ะ"""
    PurchaseItem = apps.get_model('stocks', 'PurchaseItem')
    PurchaseItem.objects.update(quantity_unit=models.F('quantity_ordered'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0057_product_cost_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomingredient',
            name='barcode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.productbarcode', verbose_name='บาร์โค้ด/หน่วยวัตถุดิบ'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='barcode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.productbarcode', verbose_name='บาร์โค้ด/หน่วยสั่งซื้อ'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_unit',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนที่สั่ง (ตามหน่วย)'),
        ),
        migrations.AddField(
            model_name='purchasereceiptlog',
            name='barcode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.productbarcode', verbose_name='บาร์โค้ด/หน่วยที่รับ'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity_ordered',
            field=models.PositiveIntegerField(verbose_name='จำนวนรวม (ชิ้น)'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptlog',
            name='quantity_received',
            field=models.PositiveIntegerField(verbose_name='จำนวนที่รับครั้งนี้ (ตามหน่วยที่เลือก)'),
        ),
        migrations.RunPython(backfill_quantity_unit, noop_reverse),
    ]
