# Generated by Django 6.0.1 on 2026-08-13 14:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0058_bomingredient_barcode_obj_purchaseitem_barcode_obj_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockForecast',
            fields=[
            ],
            options={
                'verbose_name_plural': 'C0. คาดการณ์ Stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stocks.product',),
        ),
        migrations.CreateModel(
            name='AdvanceOrderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('PURCHASE', 'ใบสั่งซื้อ'), ('PRODUCTION', 'ใบสั่งผลิต')], default='PURCHASE', max_length=10, verbose_name='ประเภท')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวนต่อครั้ง')),
                ('frequency_days', models.PositiveIntegerField(verbose_name='ความถี่ (ทุกกี่วัน)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='วันสิ้นสุด')),
                ('next_run_date', models.DateField(default=datetime.date.today, verbose_name='รอบถัดไป')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barcode_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.productbarcode', verbose_name='บาร์โค้ดที่จะผลิต')),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.bom', verbose_name='สูตรที่ใช้ผลิต')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.product', verbose_name='สินค้า')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.supplier', verbose_name='ผู้จำหน่าย')),
            ],
            options={
                'verbose_name_plural': 'B7. ใบสั่งผลิต/ใบสั่งซื้อล่วงหน้า',
            },
        ),
    ]
