# Generated by Django 6.0.1 on 2026-08-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0060_advanceorderrule_fo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ราคาขาย'),
        ),
    ]
