# Generated by Django 6.0.1 on 2026-08-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0061_salesitem_sale_price_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='เลขประจำตัวผู้เสียภาษี'),
        ),
    ]
