# Generated by Django 6.0.1 on 2026-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0062_customer_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='รหัสผู้ซื้อ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='รหัสผู้ขาย'),
        ),
    ]
