# Generated by Django 6.0.1 on 2026-08-23 13:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0063_customer_buyer_code_customer_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อคลัง')),
                ('type', models.CharField(choices=[('normal', 'ปกติ'), ('scrap', 'เศษเสีย')], default='normal', max_length=10, verbose_name='ประเภทคลัง')),
                ('is_default', models.BooleanField(default=False, help_text='สินค้าทุกรายการอยู่คลังนี้เป็นค่าเริ่มต้น (ใช้ค่า stock_quantity เดิมของสินค้าโดยตรง) มีได้คลังเดียวเท่านั้น', verbose_name='คลังหลัก (ค่าเริ่มต้น)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'A4.1 คลังสินค้า (Warehouse)',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='เลขที่เอกสาร')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวน')),
                ('transfer_date', models.DateField(default=datetime.date.today, verbose_name='วันที่โอนย้าย')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.product', verbose_name='สินค้า')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='stocks.warehouse', verbose_name='คลังต้นทาง')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='stocks.warehouse', verbose_name='คลังปลายทาง')),
            ],
            options={
                'verbose_name_plural': 'A4.2 โอนย้ายคลังสินค้า (Stock Transfer)',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='stocks.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='stocks.warehouse')),
            ],
            options={
                'verbose_name_plural': 'สต๊อกแยกคลัง',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
