# Generated by Django 6.0.1 on 2026-08-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0065_seed_default_warehouses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='sale_price',
        ),
    ]
