# Generated by Django 6.0.1 on 2026-08-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0066_remove_bom_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomingredient',
            name='is_scrap',
            field=models.BooleanField(default=False, help_text='ติ๊กถ้าวัตถุดิบตัวนี้ตอนผลิตจริง นอกจากตัดออกจากคลังหลักตามปกติแล้ว ให้ย้ายเข้าคลังเศษเสียด้วย', verbose_name='เศษเสีย'),
        ),
        migrations.AddField(
            model_name='productionmaterialusage',
            name='is_scrap',
            field=models.BooleanField(default=False, editable=False, help_text='คัดลอกมาจาก BOMIngredient.is_scrap ตอนสร้างใบสั่งผลิต', verbose_name='เศษเสีย'),
        ),
    ]
