# Generated by Django 6.0.1 on 2026-08-23 14:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0067_bomingredient_is_scrap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcode',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='เช่น 1 ถุง = 1.5234 kg ให้ใส่ 1.5234', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='จำนวนต่อหน่วย'),
        ),
    ]
