# Generated by Django 6.0.1 on 2026-09-08 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0068_alter_productbarcode_conversion_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='เลขที่ใบเสร็จ')),
                ('shipped_date', models.DateField(db_index=True, editable=False, verbose_name='วันที่')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='วันครบกำหนด')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='รวมเป็นเงิน')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='ภาษีมูลค่าเพิ่ม')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='ยอดรวมสุทธิ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='stocks.salesorder', verbose_name='ใบสั่งขายอ้างอิง')),
            ],
            options={
                'verbose_name': 'ใบเสร็จรับเงิน',
                'verbose_name_plural': 'B7. ใบเสร็จรับเงิน (Receipt)',
                'ordering': ('-shipped_date', '-id'),
                'unique_together': {('sales_order', 'shipped_date')},
            },
        ),
    ]
