# Generated by Django 6.0.1 on 2026-09-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0070_backfill_sales_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'ใบกำกับภาษี/ใบส่งของ',
                'verbose_name_plural': 'B8. ใบกำกับภาษี/ใบส่งของ (Invoice)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stocks.salesreceipt',),
        ),
    ]
