# Generated by Django 6.0.1 on 2026-09-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0071_salesinvoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advanceorderrule',
            options={'verbose_name_plural': 'A6. ใบสั่งผลิต/ใบสั่งซื้อล่วงหน้า'},
        ),
    ]
