# Generated by Django 6.0.1 on 2026-09-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0072_alter_advanceorderrule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advanceorderrule',
            options={'verbose_name_plural': 'F3. ใบสั่งผลิต/ใบสั่งซื้อล่วงหน้า'},
        ),
        migrations.AlterModelOptions(
            name='bom',
            options={'verbose_name_plural': 'O1. สูตรการผลิต (BOM)'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'S1. ลูกค้า (Customer)'},
        ),
        migrations.AlterModelOptions(
            name='customerproductcontract',
            options={'verbose_name_plural': 'S4. ราคาสัญญา&DC/Rebate'},
        ),
        migrations.AlterModelOptions(
            name='financereport',
            options={'verbose_name_plural': 'F4. สรุปรายจ่าย (PO Report)'},
        ),
        migrations.AlterModelOptions(
            name='incomereport',
            options={'verbose_name': 'F5. สรุปรายรับ (SO Report)', 'verbose_name_plural': 'F5. สรุปรายรับ (SO Report)'},
        ),
        migrations.AlterModelOptions(
            name='internationalpurchasetracking',
            options={'verbose_name': 'P4. ติดตามสินค้าต่างประเทศ', 'verbose_name_plural': 'P4. ติดตามสินค้าต่างประเทศ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'W1. รายการสินค้า (Product)'},
        ),
        migrations.AlterModelOptions(
            name='productbarcode',
            options={'verbose_name_plural': 'W6. หน่วยขายตามบาร์โค้ด'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'W2. กลุ่มสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='productionorder',
            options={'verbose_name_plural': 'O2. ใบสั่งผลิต (Productions)'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'แท็กสินค้า', 'verbose_name_plural': 'W5. แท็กสินค้า (Product Tag)'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name_plural': 'P2. ใบสั่งซื้อ (Purchase)'},
        ),
        migrations.AlterModelOptions(
            name='purchasequotation',
            options={'verbose_name': 'ใบเสนอราคาซื้อ', 'verbose_name_plural': 'P3. ใบเสนอราคาซื้อ (Purchase Quotation)'},
        ),
        migrations.AlterModelOptions(
            name='rebatepayout',
            options={'verbose_name': 'สรุปสัญญา Rebate', 'verbose_name_plural': 'A4. สรุปสัญญา Rebate'},
        ),
        migrations.AlterModelOptions(
            name='salescontract',
            options={'verbose_name': 'A5. สัญญาการขาย', 'verbose_name_plural': 'A5. สัญญาการขาย'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'verbose_name': 'ใบกำกับภาษี/ใบส่งของ', 'verbose_name_plural': 'A2. ใบกำกับภาษี/ใบส่งของ (Invoice)'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name_plural': 'S2. ใบสั่งขาย (Sales)'},
        ),
        migrations.AlterModelOptions(
            name='salesquotation',
            options={'verbose_name': 'ใบเสนอราคาขาย', 'verbose_name_plural': 'S3. ใบเสนอราคาขาย (Sales Quotation)'},
        ),
        migrations.AlterModelOptions(
            name='salesreceipt',
            options={'ordering': ('-shipped_date', '-id'), 'verbose_name': 'ใบเสร็จรับเงิน', 'verbose_name_plural': 'A1. ใบเสร็จรับเงิน (Receipt)'},
        ),
        migrations.AlterModelOptions(
            name='salesreport',
            options={'verbose_name': 'F6. รายงานยอดขายตามสินค้า', 'verbose_name_plural': 'F6. รายงานยอดขายตามสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='shipmentaccounting',
            options={'verbose_name': 'A3. การทำบัญชี DC/Rebate', 'verbose_name_plural': 'A3. การทำบัญชี DC/Rebate'},
        ),
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'verbose_name_plural': 'W7. บันทึกการปรับสต็อก'},
        ),
        migrations.AlterModelOptions(
            name='stockforecast',
            options={'verbose_name_plural': 'F2. คาดการณ์ Stock'},
        ),
        migrations.AlterModelOptions(
            name='stockplanning',
            options={'verbose_name_plural': 'F1. ตารางการวางแผนสต็อก'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'verbose_name_plural': 'W4. โอนย้ายคลังสินค้า (Stock Transfer)'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'P1. ผู้จำหน่าย (Supplier)'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name_plural': 'W3. คลังสินค้า (Warehouse)'},
        ),
    ]
