# Generated by Django 6.0.1 on 2026-09-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0073_alter_advanceorderrule_options_alter_bom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financereport',
            options={'verbose_name_plural': 'A3. สรุปรายจ่าย (PO Report)'},
        ),
        migrations.AlterModelOptions(
            name='incomereport',
            options={'verbose_name': 'A4. สรุปรายรับ (SO Report)', 'verbose_name_plural': 'A4. สรุปรายรับ (SO Report)'},
        ),
        migrations.AlterModelOptions(
            name='rebatepayout',
            options={'verbose_name': 'สรุปสัญญา Rebate', 'verbose_name_plural': 'A6. สรุปสัญญา Rebate'},
        ),
        migrations.AlterModelOptions(
            name='salescontract',
            options={'verbose_name': 'A7. สัญญาการขาย', 'verbose_name_plural': 'A7. สัญญาการขาย'},
        ),
        migrations.AlterModelOptions(
            name='salesreport',
            options={'verbose_name': 'F4. รายงานยอดขายตามสินค้า', 'verbose_name_plural': 'F4. รายงานยอดขายตามสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='shipmentaccounting',
            options={'verbose_name': 'A5. การทำบัญชี DC/Rebate', 'verbose_name_plural': 'A5. การทำบัญชี DC/Rebate'},
        ),
    ]
