# Generated by Django 6.0.1 on 2026-09-24 00:26

from django.db import migrations, models


def fix_uppercase_completed(apps, schema_editor):
    # action "ปิดยอดกรณีพิเศษ" เคยบันทึก status='COMPLETED' (ตัวพิมพ์ใหญ่) ซึ่งไม่ตรงกับ choices 'Completed'
    for name in ('PurchaseOrder', 'SalesOrder'):
        apps.get_model('stocks', name).objects.filter(status='COMPLETED').update(status='Completed')


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0074_alter_financereport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', '🔴 ยังไม่จ่าย'), ('Partial', '🟠 จ่ายบางส่วน'), ('Paid', '🟢 จ่ายครบแล้ว'), ('SETTLED', '⚪ ปิดยอดกรณีพิเศษ')], default='Unpaid', max_length=20, verbose_name='สถานะการเงิน'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', '🔴 ยังไม่รับเงิน'), ('Partial', '🟠 รับเงินบางส่วน'), ('Paid', '🟢 รับเงินครบแล้ว'), ('SETTLED', '⚪ ปิดยอดกรณีพิเศษ')], default='Unpaid', max_length=20, verbose_name='สถานะการรับเงิน'),
        ),
        migrations.RunPython(fix_uppercase_completed, migrations.RunPython.noop),
    ]
