# Generated by Django 6.0.1 on 2026-09-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0075_settled_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.CharField(blank=True, default='สำนักงานใหญ่', max_length=100, verbose_name='สำนักงานใหญ่/สาขา'),
        ),
    ]
