# Generated by Django 6.0.1 on 2026-09-25 06:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0076_customer_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesreceipt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='วันที่ยกเลิก'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='ยกเลิก'),
        ),
        migrations.AlterField(
            model_name='salesdeliverylog',
            name='quantity_shipped',
            field=models.IntegerField(verbose_name='จำนวน'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='เลขที่ใบลดหนี้')),
                ('doc_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='วันที่')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='สาเหตุการลดหนี้')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='มูลค่า')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='ภาษีมูลค่าเพิ่ม')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='รวม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='stocks.salesorder', verbose_name='ใบสั่งขาย')),
            ],
            options={
                'verbose_name': 'ใบลดหนี้',
                'verbose_name_plural': 'A8. ใบลดหนี้ (Credit Note)',
                'ordering': ('-doc_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวนลดหนี้')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคา/หน่วย')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='มูลค่า')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocks.creditnote')),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='stocks.salesitem', verbose_name='รายการในใบสั่งขาย')),
            ],
            options={
                'verbose_name': 'รายการลดหนี้',
                'verbose_name_plural': 'รายการลดหนี้',
            },
        ),
        migrations.AddField(
            model_name='salesdeliverylog',
            name='credit_note_item',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_log', to='stocks.creditnoteitem', verbose_name='ใบลดหนี้'),
        ),
    ]
