# Generated by Django 6.0.1 on 2026-09-25 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0077_credit_note_and_cancelled_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='stocks.salesreceipt', verbose_name='ใบกำกับภาษี/ใบส่งของ'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='sales_order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='stocks.salesorder', verbose_name='ใบสั่งขาย'),
        ),
    ]
