# Generated by Django 6.0.1 on 2026-09-29 11:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_bank_transactions(apps, schema_editor):
    """สร้างรายการเดินบัญชีย้อนหลังจากการรับ/จ่ายเงินที่มีอยู่แล้ว (ยังไม่ระบุสมุดบัญชี)"""
    BankTransaction = apps.get_model('stocks', 'BankTransaction')
    SalesPayment = apps.get_model('stocks', 'SalesPayment')
    PurchasePaymentLog = apps.get_model('stocks', 'PurchasePaymentLog')
    RebatePayout = apps.get_model('stocks', 'RebatePayout')
    rows = []
    for p in SalesPayment.objects.select_related('order', 'order__customer'):
        remark = p.remark or ''
        deduction = p.amount < 0 and ('DC' in remark or 'Rebate' in remark)
        rows.append(BankTransaction(
            sales_payment=p, txn_date=p.payment_date, amount=p.amount,
            source_type='DC_REBATE' if deduction else 'SALES_PAYMENT',
            reference=p.order.so_number or '',
            party=p.order.customer.company_name if p.order.customer_id else '',
            description=(remark or 'รับเงินขาย')[:255]))
    for p in PurchasePaymentLog.objects.select_related('purchase_order', 'purchase_order__supplier'):
        po = p.purchase_order
        rows.append(BankTransaction(
            purchase_payment=p, txn_date=p.payment_date, amount=-p.amount, source_type='PURCHASE_PAYMENT',
            reference=po.po_number or '', party=po.supplier.company_name if po.supplier_id else '',
            description=(p.notes or 'จ่ายเงินซื้อ')[:255], created_by_id=p.user_id))
    for p in RebatePayout.objects.filter(status='PAID').select_related('contract', 'contract__customer'):
        c = p.contract
        rows.append(BankTransaction(
            rebate_payout=p, txn_date=p.payout_date, amount=-p.rebate_amount, source_type='REBATE_PAYOUT',
            reference=p.ref_invoice or c.contract_name, party=c.customer.company_name,
            description=f"จ่าย Rebate {c.contract_name} ({p.period_start:%d/%m/%Y}–{p.period_end:%d/%m/%Y})"[:255]))
    BankTransaction.objects.bulk_create(rows, batch_size=500)
    RebatePayout.objects.filter(status='PAID', paid_date__isnull=True).update(paid_date=models.F('payout_date'))


DEFAULT_CATEGORIES = ['ค่าแรง', 'เงินเดือน', 'ค่าเช่า', 'ค่าน้ำ/ค่าไฟ/โทรศัพท์', 'ค่าธรรมเนียมธนาคาร',
                      'ภาษี', 'โอนระหว่างบัญชี', 'รายรับอื่นๆ', 'รายจ่ายอื่นๆ']


def seed_categories(apps, schema_editor):
    Category = apps.get_model('stocks', 'BankTransactionCategory')
    for name in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0078_creditnote_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อบัญชี')),
                ('account_type', models.CharField(choices=[('SAVINGS', 'ออมทรัพย์'), ('CURRENT', 'กระแสรายวัน (เช็ค)'), ('CREDIT', 'เครดิต'), ('CASH', 'เงินสด'), ('FACTORING', 'แฟคตอริ่ง')], default='SAVINGS', max_length=20, verbose_name='ประเภทบัญชี')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='ธนาคาร/สถาบัน')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='สาขา')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='เลขที่บัญชี')),
                ('opening_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='ยอดยกมา')),
                ('opening_date', models.DateField(default=datetime.date.today, verbose_name='วันที่ยอดยกมา')),
                ('is_default', models.BooleanField(default=False, help_text='รายการรับ/จ่ายที่ไม่ได้เลือกบัญชี (เช่น ยืนยันยอดจาก A5) จะเข้าบัญชีนี้', verbose_name='บัญชีหลัก')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'สมุดบัญชี',
                'verbose_name_plural': 'M1. สมุดบัญชี',
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BankTransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวด')),
            ],
            options={
                'verbose_name': 'หมวดรายการเดินบัญชี',
                'verbose_name_plural': 'หมวดรายการเดินบัญชี',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='rebatepayout',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่จ่ายจริง'),
        ),
        migrations.AddField(
            model_name='purchasepaymentlog',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stocks.bankaccount', verbose_name='สมุดบัญชี'),
        ),
        migrations.AddField(
            model_name='rebatepayout',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stocks.bankaccount', verbose_name='จ่ายจากสมุดบัญชี'),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stocks.bankaccount', verbose_name='สมุดบัญชี'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อ/เลขที่สัญญากู้')),
                ('lender', models.CharField(max_length=255, verbose_name='ผู้ให้กู้')),
                ('principal', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ยอดกู้')),
                ('loan_date', models.DateField(default=datetime.date.today, verbose_name='วันที่รับเงินกู้')),
                ('first_due_date', models.DateField(help_text='งวดถัดไปครบกำหนดวันเดียวกันของทุกเดือน', verbose_name='วันครบกำหนดงวดแรก')),
                ('term_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='จำนวนงวด (เดือน)')),
                ('repayment_method', models.CharField(choices=[('ANNUITY', 'ผ่อนเท่ากันทุกงวด (เงินต้น+ดอกเบี้ย)'), ('EQUAL_PRINCIPAL', 'เงินต้นเท่ากันทุกงวด + ดอกเบี้ยตามยอดคงเหลือ'), ('FIXED_PAYMENT', 'ระบุยอดผ่อนต่องวดเอง (งวดสุดท้ายจ่ายส่วนที่เหลือ)')], default='ANNUITY', max_length=20, verbose_name='วิธีผ่อน')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=4, help_text='ใช้กับวิธี "ระบุยอดผ่อนต่องวดเอง"', max_digits=18, null=True, verbose_name='ยอดผ่อนต่องวด')),
                ('interest_method', models.CharField(choices=[('MONTHLY', 'รายเดือน (อัตราต่อปี ÷ 12)'), ('DAILY', 'รายวันตามจริง (อัตราต่อปี × จำนวนวัน ÷ 365)')], default='MONTHLY', max_length=10, verbose_name='วิธีคิดดอกเบี้ย')),
                ('record_disbursement', models.BooleanField(default=True, help_text='สร้างรายการเงินเข้า (ยอดกู้) ในวันที่รับเงินกู้', verbose_name='บันทึกเงินกู้เข้าสมุดบัญชี')),
                ('is_active', models.BooleanField(default=True, help_text='ปิด = หยุดตัดชำระงวดที่ถึงกำหนดอัตโนมัติ', verbose_name='ใช้งาน')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='stocks.bankaccount', verbose_name='สมุดบัญชี (รับเงินกู้/ตัดชำระ)')),
            ],
            options={
                'verbose_name': 'เงินกู้',
                'verbose_name_plural': 'M3. เงินกู้',
                'ordering': ('-loan_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_no', models.PositiveSmallIntegerField(verbose_name='งวดที่')),
                ('due_date', models.DateField(db_index=True, verbose_name='วันครบกำหนด')),
                ('annual_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='ดอกเบี้ย %')),
                ('principal_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='เงินต้น')),
                ('interest_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='ดอกเบี้ย')),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='ยอดชำระ')),
                ('balance_after', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='เงินต้นคงเหลือ')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='stocks.loan')),
            ],
            options={
                'verbose_name': 'งวดผ่อนชำระ',
                'verbose_name_plural': 'ตารางผ่อนชำระ',
                'ordering': ('period_no', 'due_date'),
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='วันที่')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='จำนวนเงิน (+เข้า / -ออก)')),
                ('source_type', models.CharField(choices=[('MANUAL', 'บันทึกเอง'), ('SALES_PAYMENT', 'รับเงินขาย (A4/A5)'), ('DC_REBATE', 'หัก DC/Rebate (A5)'), ('PURCHASE_PAYMENT', 'จ่ายเงินซื้อ (A3)'), ('REBATE_PAYOUT', 'จ่าย Rebate ตามสัญญา (A6)'), ('LOAN_DISBURSE', 'รับเงินกู้ (M3)'), ('LOAN_PAYMENT', 'ผ่อนชำระเงินกู้ (M3)')], db_index=True, default='MANUAL', editable=False, max_length=20, verbose_name='ที่มา')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='เอกสารอ้างอิง')),
                ('party', models.CharField(blank=True, max_length=255, verbose_name='คู่ค้า')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stocks.bankaccount', verbose_name='สมุดบัญชี')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('purchase_payment', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_txn', to='stocks.purchasepaymentlog')),
                ('rebate_payout', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_txn', to='stocks.rebatepayout')),
                ('sales_payment', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_txn', to='stocks.salespayment')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stocks.banktransactioncategory', verbose_name='หมวด')),
                ('loan_disbursement', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_txn', to='stocks.loan')),
                ('loan_installment', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_txn', to='stocks.loaninstallment')),
            ],
            options={
                'verbose_name': 'รายการเดินบัญชี',
                'verbose_name_plural': 'M2. รายการเดินบัญชี',
                'ordering': ('-txn_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LoanRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_period', models.PositiveSmallIntegerField(blank=True, help_text='เว้นว่างทั้งสองช่อง = ตั้งแต่งวดแรก', null=True, verbose_name='เริ่มงวดที่')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='หรือ เริ่มวันที่')),
                ('annual_rate', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ดอกเบี้ย % ต่อปี')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='stocks.loan')),
            ],
            options={
                'verbose_name': 'อัตราดอกเบี้ย',
                'verbose_name_plural': 'อัตราดอกเบี้ย (กำหนดได้หลายช่วง ตามงวดหรือวันที่)',
                'ordering': ('from_period', 'from_date', 'id'),
            },
        ),
        migrations.RunPython(backfill_bank_transactions, migrations.RunPython.noop),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
