# Generated by Django 6.0.1 on 2026-09-29 12:53

from django.db import migrations, models

NEW_CATEGORIES = ['ค่าขนส่ง', 'ภาษีนำเข้า', 'ภ.พ.30']


def add_categories(apps, schema_editor):
    Category = apps.get_model('stocks', 'BankTransactionCategory')
    for name in NEW_CATEGORIES:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0079_finance_bank_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='party',
            field=models.CharField(blank=True, max_length=255, verbose_name='บริษัท/บุคคล'),
        ),
        migrations.RunPython(add_categories, migrations.RunPython.noop),
    ]
