# Generated by Django 6.0.1 on 2026-09-29 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0080_bank_party_label_more_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='advance_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='เช่น 1 = ได้รับวันถัดจากวันที่ขาย', verbose_name='รับเงินเบิกหลังวันขาย (วัน)'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='advance_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='เช่น 75 = จ่ายเข้าบัญชีที่ผูก 75%', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% เบิกล่วงหน้า'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='วงเงินเครดิต'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-31 (เดือนที่ไม่มีวันนั้นใช้วันสิ้นเดือน)', null=True, verbose_name='วันครบกำหนดชำระ (ทุกวันที่)'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='factoring_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='คิดจากยอดเบิก ตั้งแต่วันรับเงินเบิกถึงวันที่ลูกค้าจ่าย', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ดอกเบี้ยแฟคตอริ่ง (% ต่อปี)'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='linked_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stocks.bankaccount', verbose_name='บัญชีที่ผูกรับเงินโอน'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='overdue_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ดอกเบี้ยเมื่อเกินกำหนด (% ต่อปี)'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='settle_business_days',
            field=models.PositiveSmallIntegerField(default=2, help_text='นับข้ามเสาร์-อาทิตย์ เช่น 2: ลูกค้าจ่ายวันศุกร์ -> ได้รับวันอังคาร', verbose_name='รับส่วนที่เหลือหลังลูกค้าจ่าย (วันทำการ)'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='factoring_payment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factoring_txns', to='stocks.salespayment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='factoring_account',
            field=models.ForeignKey(blank=True, help_text='ใช้กับ action "ขายแฟคตอริ่ง" ในหน้าใบสั่งขาย/สรุปรายรับ (เลือกเป็นราย SO)', limit_choices_to={'account_type': 'FACTORING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stocks.bankaccount', verbose_name='บัญชีแฟคตอริ่ง'),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='factoring_customer_paid_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='factoring_rate',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='factoring_role',
            field=models.CharField(blank=True, choices=[('ADVANCE', 'เบิกล่วงหน้า'), ('REMAINDER', 'ส่วนที่เหลือ')], default='', editable=False, max_length=10, verbose_name='แฟคตอริ่ง'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'บันทึกเอง'), ('SALES_PAYMENT', 'รับเงินขาย (A4/A5)'), ('DC_REBATE', 'หัก DC/Rebate (A5)'), ('PURCHASE_PAYMENT', 'จ่ายเงินซื้อ (A3)'), ('REBATE_PAYOUT', 'จ่าย Rebate ตามสัญญา (A6)'), ('LOAN_DISBURSE', 'รับเงินกู้ (M3)'), ('LOAN_PAYMENT', 'ผ่อนชำระเงินกู้ (M3)'), ('FACTORING', 'แฟคตอริ่ง: ดอกเบี้ย/โอนเข้าบัญชีที่ผูก')], db_index=True, default='MANUAL', editable=False, max_length=20, verbose_name='ที่มา'),
        ),
    ]
