# Generated by Django 6.0.1 on 2026-09-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0081_credit_factoring_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='transfer_peer',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_mirror', to='stocks.banktransaction'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='advance_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='นับจากวันที่กด action ขายแฟคตอริ่ง: +1 = วันถัดไป, +2 = วันมะรืน', verbose_name='วันที่จ่ายเงินเบิก (+วัน)'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'บันทึกเอง'), ('SALES_PAYMENT', 'รับเงินขาย (A4/A5)'), ('DC_REBATE', 'หัก DC/Rebate (A5)'), ('PURCHASE_PAYMENT', 'จ่ายเงินซื้อ (A3)'), ('REBATE_PAYOUT', 'จ่าย Rebate ตามสัญญา (A6)'), ('LOAN_DISBURSE', 'รับเงินกู้ (M3)'), ('LOAN_PAYMENT', 'ผ่อนชำระเงินกู้ (M3)'), ('FACTORING', 'แฟคตอริ่ง: ดอกเบี้ย/โอนเข้าบัญชีที่ผูก'), ('TRANSFER', 'โอนระหว่างบัญชี (อีกฝั่ง)')], db_index=True, default='MANUAL', editable=False, max_length=20, verbose_name='ที่มา'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_close_day',
            field=models.IntegerField(default=25, help_text='ระบุวันที่ 1-31', verbose_name='วันกำหนดชำระเงิน'),
        ),
    ]
