# Generated by Django 6.0.1 on 2026-09-29 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0083_mark_old_dc_rebate_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=4, default=0, help_text='ยอดเงินในบัญชี ณ วันที่เริ่มต้นบัญชี (บัญชีเครดิตที่ใช้ไปแล้วใส่ติดลบ)', max_digits=18, verbose_name='เงินเริ่มต้นบัญชี (ยอดยกมา)'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='opening_date',
            field=models.DateField(default=datetime.date.today, help_text='รายการก่อนวันนี้ไม่นับรวมในยอดคงเหลือ (รวมอยู่ในเงินเริ่มต้นแล้ว)', verbose_name='วันที่เริ่มต้นบัญชี'),
        ),
    ]
