# Generated by Django 6.0.1 on 2026-09-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0085_bank_opening_labels_revert'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='deduct_month',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True, verbose_name='หักรอบเดือน'),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='deduction_kind',
            field=models.CharField(blank=True, choices=[('DC', 'DC'), ('REBATE', 'Rebate')], default='', editable=False, max_length=10, verbose_name='หัก'),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='deduction_log',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='stocks.salesdeliverylog'),
        ),
    ]
