# Generated by Django 6.0.1 on 2026-09-30 02:00

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0088_mark_old_revenue_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='วันที่รับเงินต้นครั้งแรก'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=18, verbose_name='เงินต้นรวม'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='record_disbursement',
            field=models.BooleanField(default=True, help_text='สร้างรายการเงินเข้าตามวันที่รับเงินต้นแต่ละครั้ง', verbose_name='บันทึกเงินต้นที่รับเข้าสมุดบัญชี'),
        ),
        migrations.CreateModel(
            name='LoanDrawdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(default=datetime.date.today, verbose_name='วันที่รับเงินต้น')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='เงินต้นที่รับ')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdowns', to='stocks.loan')),
            ],
            options={
                'verbose_name': 'รับเงินต้น',
                'verbose_name_plural': 'รับเงินต้น (รับได้หลายครั้ง — ดอกเบี้ยนับจากวันที่รับ)',
                'ordering': ('draw_date', 'id'),
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='loan_drawdown',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_txn', to='stocks.loandrawdown'),
        ),
    ]
