# Generated by Django 6.0.1 on 2026-09-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0090_loan_drawdowns_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='loan_disbursement',
        ),
    ]
