# Generated by Django 6.0.1 on 2026-10-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0091_remove_loan_disbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='ว่าง = ทุกลูกค้า (All) / ระบุ = ใช้สูตรนี้เฉพาะ SO ของลูกค้ารายนี้', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_formulas', to='stocks.customer', verbose_name='ลูกค้า'),
        ),
    ]
