# Generated by Django 6.0.1 on 2026-10-02 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0093_customer_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_day_2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ใช้กับรอบครึ่งเดือน เช่น รอบ 1-15 จ่ายวันที่ 18 / รอบ 16-สิ้นเดือน จ่ายวันที่ 3 (ว่าง = ใช้วันเดียวกับรอบ 1-15)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='วันกำหนดชำระเงิน รอบ 16-สิ้นเดือน'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_day',
            field=models.IntegerField(default=25, help_text='ระบุวันที่ 1-31 (เกินวันสิ้นเดือน = สิ้นเดือน) — รอบครึ่งเดือน: ใช้กับรอบ 1-15', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='วันกำหนดชำระเงิน'),
        ),
    ]
