# Generated by Django 6.0.1 on 2026-10-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0095_customer_receiving_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='advance_days',
        ),
    ]
