# Generated by Django 6.0.1 on 2026-10-05 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0096_remove_bankaccount_advance_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='factoring_fee_percent',
            field=models.DecimalField(decimal_places=4, default=0, help_text='คิดจากยอดที่ขาย หักจากเงินเบิกล่วงหน้า เช่น ขาย 1,000 เบิก 80% ค่าธรรมเนียม 5% -> ได้รับ 800 - 50 = 750', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% ค่าธรรมเนียม'),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='factoring_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=8, null=True),
        ),
    ]
