# Generated by Django 6.0.1 on 2026-10-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0098_salespayment_factoring_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='batch_ref',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='purchasepaymentlog',
            name='batch_ref',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='batch_ref',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=32),
        ),
    ]
