# Generated by Django 6.0.1 on 2026-10-06 16:32

from django.db import migrations, models
from django.utils import timezone


def mark_factored(apps, schema_editor):
    # ใบที่ขายแฟคตอริ่งไปแล้ว (เดิมขึ้นรับเงินครบแล้วทันที) แต่ส่วนที่เหลือยังไม่ถึงวันรับเงิน -> ขายแฟคตอริ่งแล้ว
    SalesOrder = apps.get_model('stocks', 'SalesOrder')
    SalesPayment = apps.get_model('stocks', 'SalesPayment')
    pending = SalesPayment.objects.filter(factoring_role='REMAINDER', payment_date__gt=timezone.localdate()
                                          ).values('order_id')
    SalesOrder.objects.filter(payment_status='Paid', pk__in=pending).update(payment_status='FACTORED')


def unmark_factored(apps, schema_editor):
    apps.get_model('stocks', 'SalesOrder').objects.filter(payment_status='FACTORED').update(payment_status='Paid')


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0099_payment_batch_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', '🔴 ยังไม่รับเงิน'), ('Partial', '🟠 รับเงินบางส่วน'), ('FACTORED', '🔵 ขายแฟคตอริ่งแล้ว'), ('Paid', '🟢 รับเงินครบแล้ว'), ('SETTLED', '⚪ ปิดยอดกรณีพิเศษ')], default='Unpaid', max_length=20, verbose_name='สถานะการรับเงิน'),
        ),
        migrations.RunPython(mark_factored, unmark_factored),
    ]
