# Generated by Django 6.0.1 on 2026-10-07 01:35

from django.db import migrations, models


def recompute_factoring(apps, schema_editor):
    # ไอร่าหักดอกเบี้ยทันทีวันจ่ายเงินเบิก -> รายการเดิมทั้งหมดเป็น "หักทันที" (ค่าเริ่มต้นของบัญชี)
    # แล้วคำนวณสมุดแฟคตอริ่งใหม่: ดอกเบี้ยย้ายไปวันเงินเบิกเข้า, ค่าธรรมเนียม/ดอกเบี้ยรวมเป็นก้อนต่อวัน
    # ใช้โมเดลจริง (ตรรกะอยู่ในฟังก์ชันแฟคตอริ่ง) เหมือน 0102
    from stocks.models import SalesPayment, sync_factoring_settlement, rebuild_factoring_transfers
    SalesPayment.objects.filter(factoring_role='ADVANCE').update(factoring_interest_upfront=True)
    for order_id in set(SalesPayment.objects.exclude(factoring_role='').values_list('order_id', flat=True)):
        sync_factoring_settlement(order_id)
    rebuild_factoring_transfers()


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0102_recompute_so_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='factoring_doc_form',
            field=models.CharField(choices=[('AIRA', 'ไอร่า (DETAILS OF DEBTS PURCHASED)')], default='AIRA', help_text='รูปแบบเอกสารรายการรับซื้อหนี้ในหน้า "รายการเอกสาร" (แต่ละแฟคตอริ่งมีฟอร์มของตัวเองได้)', max_length=20, verbose_name='แบบฟอร์มเอกสาร'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='factoring_interest_timing',
            field=models.CharField(choices=[('UPFRONT', 'หักดอกเบี้ยทันที (วันที่จ่ายเงินเบิก)'), ('LATER', 'หักดอกเบี้ยภายหลัง (วันที่ลูกค้าจ่าย)')], default='UPFRONT', help_text='ทันที: หักจากเงินเบิกวันที่แฟคตอริ่งจ่ายเงินให้เรา (คิดล่วงหน้าถึงวันที่ลูกค้าจ่าย) เช่น ไอร่า / ภายหลัง: หักจากส่วนที่เหลือตอนลูกค้าจ่าย', max_length=10, verbose_name='การหักดอกเบี้ย'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='factoring_charge',
            field=models.CharField(blank=True, choices=[('FEE', 'ค่าธรรมเนียมแฟคตอริ่ง'), ('INTEREST', 'ดอกเบี้ยแฟคตอริ่ง')], default='', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='factoring_fee',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='factoring_interest',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='factoring_interest_upfront',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(recompute_factoring, migrations.RunPython.noop),
    ]
