# Generated by Django 6.0.1 on 2026-10-07 01:44

from django.db import migrations, models


def fill_deduct_month(apps, schema_editor):
    # ใบเดิม: ใบที่ขายแฟคตอริ่งเคยถูกหักในเดือนที่ลูกค้าจ่ายส่วนที่เหลือ -> ใช้เดือนนั้น (สมุดบัญชีไม่เปลี่ยน)
    # ใบอื่นใช้เดือนของวันที่ใบลดหนี้
    CreditNote = apps.get_model('stocks', 'CreditNote')
    SalesPayment = apps.get_model('stocks', 'SalesPayment')
    for cn in CreditNote.objects.all():
        rows = SalesPayment.objects.filter(factoring_role='REMAINDER', order_id=cn.sales_order_id)
        rows = rows.filter(receipt_id=cn.receipt_id) if rows.filter(receipt_id=cn.receipt_id).exists()             else rows.filter(receipt__isnull=True)
        paid = rows.order_by('factoring_customer_paid_date').values_list('factoring_customer_paid_date',
                                                                         flat=True).first()
        cn.deduct_month = (paid or cn.doc_date).replace(day=1)
        cn.save(update_fields=['deduct_month'])


def recompute_factoring(apps, schema_editor):
    # คำนวณสมุดแฟคตอริ่งใหม่ทั้งหมด: ดอกเบี้ยหักทันทีย้ายไปวันเงินเบิกเข้า, ค่าธรรมเนียม/ดอกเบี้ยรวมก้อนต่อวัน,
    # DC/Rebate/ลดหนี้รวมแถวเดียว — ใช้โมเดลจริง (ตรรกะอยู่ในฟังก์ชันแฟคตอริ่ง) ต้องอยู่ migration สุดท้ายของชุดนี้
    from stocks.models import SalesPayment, sync_factoring_settlement, rebuild_factoring_transfers
    for order_id in set(SalesPayment.objects.exclude(factoring_role='').values_list('order_id', flat=True)):
        sync_factoring_settlement(order_id)
    rebuild_factoring_transfers()


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0103_factoring_interest_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='deduct_month',
            field=models.DateField(blank=True, null=True, verbose_name='หักจากยอดชำระเดือน'),
        ),
        migrations.RunPython(fill_deduct_month, migrations.RunPython.noop),
        migrations.RunPython(recompute_factoring, migrations.RunPython.noop),
    ]
