# Generated by Django 6.0.1 on 2026-10-07 02:31

from django.db import migrations, models


def fill_due_date(apps, schema_editor):
    # วันครบกำหนดตอนขาย: ราย IV = วันครบกำหนดของใบ (ไม่ก่อนวันเงินเบิก) / ทั้ง SO = วันลูกค้าจ่ายที่บันทึกไว้
    SalesPayment = apps.get_model('stocks', 'SalesPayment')
    for r in SalesPayment.objects.filter(factoring_role='REMAINDER').select_related('receipt'):
        due = r.factoring_customer_paid_date
        if r.receipt_id and r.receipt.due_date:
            adv = (SalesPayment.objects.filter(order_id=r.order_id, receipt_id=r.receipt_id, factoring_role='ADVANCE')
                   .values_list('payment_date', flat=True).first())
            due = max(r.receipt.due_date, adv) if adv else r.receipt.due_date
        r.factoring_due_date = due
        r.save(update_fields=['factoring_due_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0104_creditnote_deduct_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='factoring_due_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='settle_business_days',
            field=models.PositiveSmallIntegerField(default=2, help_text='นับข้ามวันหยุด (เสาร์-อาทิตย์, 31 ธ.ค., 1 ม.ค.) เช่น 2: ลูกค้าจ่ายวันศุกร์ -> ได้รับวันอังคาร', verbose_name='รับส่วนที่เหลือหลังลูกค้าจ่าย (วันทำการ)'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='factoring_charge',
            field=models.CharField(blank=True, choices=[('FEE', 'ค่าธรรมเนียมแฟคตอริ่ง'), ('INTEREST', 'ดอกเบี้ยแฟคตอริ่ง'), ('REFUND', 'ค่าโอนสิทธิส่งคืน')], default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shift_weekend_to_monday',
            field=models.BooleanField(default=True, help_text='วันหยุด = เสาร์-อาทิตย์, 31 ธ.ค., 1 ม.ค. (เช่น ครบ 1 ม.ค. 2570 วันศุกร์ -> 4 ม.ค.)', verbose_name='ครบกำหนดตรงวันหยุด เลื่อนเป็นวันทำการถัดไป'),
        ),
        migrations.RunPython(fill_due_date, migrations.RunPython.noop),
    ]
