# Generated by Django 6.0.1 on 2026-10-07 02:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def recompute(apps, schema_editor):
    # ใช้โค้ดจริง — ต้องอยู่ migration สุดท้ายของชุดนี้ (0103-0105 ไม่เรียกโค้ดจริงแล้ว)
    # 1) สมุดแฟคตอริ่งทั้งหมด: ค่าธรรมเนียมรวมต่อ Batch (ขั้นต่ำ), ดอกเบี้ยหักทันทีถึงวันครบกำหนด + ส่งคืน/เก็บเพิ่มตอนลูกค้าจ่าย, ก้อนรวมต่อวัน
    # 2) วันครบกำหนดของ IV ค้างรับ (ยังไม่ขายแฟคตอริ่ง) ตามวันหยุดใหม่ 31 ธ.ค. / 1 ม.ค.
    from stocks.models import (Customer, SalesPayment, recompute_customer_due_dates, rebuild_factoring_transfers,
                               sync_factoring_settlement)
    for order_id in set(SalesPayment.objects.exclude(factoring_role='').values_list('order_id', flat=True)):
        sync_factoring_settlement(order_id)
    rebuild_factoring_transfers()
    for customer in Customer.objects.filter(shift_weekend_to_monday=True):
        recompute_customer_due_dates(customer)


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0105_factoring_due_date_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='factoring_fee_minimum',
            field=models.DecimalField(decimal_places=4, default=0, help_text='ต่อลูกหนี้ต่อวันเงินเบิก (Batch) — % ค่าธรรมเนียมได้น้อยกว่านี้ เก็บเท่านี้ (0 = ไม่มีขั้นต่ำ)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ค่าธรรมเนียมขั้นต่ำ ต่อลูกหนี้'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='factoring_wht_percent',
            field=models.DecimalField(decimal_places=4, default=0, help_text='คิดจาก (ค่าโอนสิทธิเรียกร้อง + ค่าธรรมเนียม) ของเอกสารรับซื้อหนี้ แฟคตอริ่งบวกคืนในยอดโอน — กรอกยอดจริงทับรายเอกสารได้ในหน้าเอกสาร', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% ภาษีหัก ณ ที่จ่าย (แฟคตอริ่งคืน)'),
        ),
        migrations.CreateModel(
            name='FactoringDocAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_date', models.DateField()),
                ('wht_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ภาษีหัก ณ ที่จ่าย')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factoring_doc_adjustments', to='stocks.bankaccount')),
            ],
            options={
                'verbose_name': 'ปรับยอดเอกสารแฟคตอริ่ง',
                'verbose_name_plural': 'ปรับยอดเอกสารแฟคตอริ่ง',
                'unique_together': {('bank_account', 'doc_date')},
            },
        ),
        migrations.RunPython(recompute, migrations.RunPython.noop),
    ]
