# Generated by Django 6.0.1 on 2026-10-07 02:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def clear_before_latest(apps, schema_editor):
    # ภาษีที่กรอกไว้ในเอกสารล่าสุด (เช่น 2,924.48 วันที่ 06/10) = คืนครบถึงฉบับนั้นแล้ว -> เอกสารรับซื้อหนี้
    # ตั้งแต่ฉบับนั้นย้อนหลังไม่มีภาษีค้าง (ผู้ใช้ยืนยัน 2026-10-07)
    Adj = apps.get_model('stocks', 'FactoringDocAdjustment')
    SalesPayment = apps.get_model('stocks', 'SalesPayment')
    for account_id in set(Adj.objects.filter(wht_amount__gt=0).values_list('bank_account_id', flat=True)):
        latest = Adj.objects.filter(bank_account_id=account_id, wht_amount__gt=0).order_by('-doc_date').first()
        days = set(SalesPayment.objects.filter(bank_account_id=account_id, factoring_role='ADVANCE',
                                               payment_date__lte=latest.doc_date)
                   .values_list('payment_date', flat=True))
        for day in days:
            adj, _ = Adj.objects.get_or_create(bank_account_id=account_id, doc_date=day)
            if adj.wht_cleared_by_id is None:
                adj.wht_cleared_by_id = latest.pk
                adj.save(update_fields=['wht_cleared_by'])


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0106_factoring_fee_minimum_wht'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoringdocadjustment',
            name='wht_cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_cleared_docs', to='stocks.factoringdocadjustment'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='factoring_wht_percent',
            field=models.DecimalField(decimal_places=4, default=0, help_text='ภาษีค้างคืน = (ค่าโอนสิทธิเรียกร้อง + ค่าธรรมเนียม) ของเอกสารรับซื้อหนี้ × % นี้ — ใส่เข้าเอกสารที่แฟคตอริ่งคืนด้วย action "คำนวณภาษีหัก ณ ที่จ่าย"', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% ภาษีหัก ณ ที่จ่าย (แฟคตอริ่งคืน)'),
        ),
        migrations.RunPython(clear_before_latest, migrations.RunPython.noop),
    ]
