# Generated by Django 6.0.1 on 2026-10-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0108_recalc_self_referencing_bom_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReport",
            fields=[],
            options={
                "verbose_name": "F5. รายงานยอดสั่งซื้อตามสินค้า",
                "verbose_name_plural": "F5. รายงานยอดสั่งซื้อตามสินค้า",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stocks.product",),
        ),
    ]
