# Generated by Django 6.0.1 on 2026-10-08 12:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def existing_payments_thb(apps, schema_editor):
    # รายการจ่ายเงินเดิมทั้งหมดเป็นบาท -> เรท 1 (ใบสั่งซื้อ/ราคา Supplier เดิมได้ บาท + เรท 1 จากค่าเริ่มต้นของฟิลด์)
    apps.get_model('stocks', 'PurchasePaymentLog').objects.filter(exchange_rate__isnull=True).update(exchange_rate=1)


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0109_purchasereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsupplier",
            name="currency",
            field=models.CharField(
                choices=[("THB", "บาท"), ("RMB", "RMB"), ("USD", "USD")],
                default="THB",
                max_length=3,
                verbose_name="สกุลเงิน",
            ),
        ),
        migrations.AddField(
            model_name="productsupplier",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="บาทต่อ 1 หน่วยเงิน (บาท = 1)",
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
                verbose_name="ExRate",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="currency",
            field=models.CharField(
                choices=[("THB", "บาท"), ("RMB", "RMB"), ("USD", "USD")],
                default="THB",
                max_length=3,
                verbose_name="สกุลเงิน",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="บาทต่อ 1 หน่วยเงิน (บาท = 1)",
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
                verbose_name="ExRate",
            ),
        ),
        migrations.AddField(
            model_name="purchasepaymentlog",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="ว่าง = ใช้เรทของใบสั่งซื้อ (บาท = 1)",
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
                verbose_name="ExRate",
            ),
        ),
        migrations.AlterField(
            model_name="purchasepaymentlog",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="เป็นสกุลเงินของใบสั่งซื้อ",
                max_digits=12,
                verbose_name="ยอดที่จ่าย",
            ),
        ),
        migrations.RunPython(existing_payments_thb, migrations.RunPython.noop),
    ]
