# Generated by Django 6.0.1 on 2026-10-08 14:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0110_purchase_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auto_cost',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, verbose_name='ต้นทุนอัตโนมัติ (Supplier+15%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='ราคาทุน (ใช้จริง)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual_buy_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, verbose_name='ต้นทุน (กำหนดเอง)'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='latest_buy_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='ทุนล่าสุดจากเจ้านี้'),
        ),
        migrations.AlterField(
            model_name='purchasepaymentlog',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='เรทตอนจ่ายจริง บาทต่อ 1 หน่วยเงิน (บาท = 1)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='ExRate'),
        ),
    ]
